/**
 * Purpose: let user guess a random number generated by computer
 * 
 * @author Birkhoff Cheng
 * @version 0.0.1
 * PMR:
 * This is a nice practice.
 * When having a loop, you can't declare variables in the loop, so always declare them at the beginning.
 */
import java.util.Scanner;
public class GuessingGameV1
{
	public static void main(String[] args)
	{
		//setting scanner
		Scanner in = new Scanner(System.in);

		//declaring variables
		int random = (int) ( Math.random() * 100 );
		System.out.println("We have generated a random integer between 1 and 100. Guess what it is!");
		boolean correct = false;
		String guessStr;
		int guess;
		int numberOfGuesses = 0;

		//guess
		while ( !correct ) {
			System.out.print("Enter your guess: ");
			guessStr = in.next();
			guess = Integer.parseInt(guessStr);
			numberOfGuesses++;
			if ( guess == random ) {
				correct = true;
				System.out.println("Congratulations!\nThe random number was " + random);
				System.out.println("Number of guesses: " + numberOfGuesses);
			} else if ( guess <= 100 && guess > random ) {
				System.out.println("Too high");
			} else if ( guess >= 1 && guess < random ) {
				System.out.println("Too low");
			} else {
				System.out.println("Invalid input! Please enter an integer between 1 and 100!");
			}
		}
	}
}
